#nullable disable
namespace System.Web.Security
{
  internal interface IMembershipAdapter
  {
    MembershipProviderCollection Providers { get; }

    int UserIsOnlineTimeWindow { get; }

    bool IsDecryptionKeyAutogenerated { get; }

    bool UsingCustomEncryption { get; }

    byte[] EncryptOrDecryptData(bool encrypt, byte[] buffer, bool useLegacyMode);
  }
}
