// <auto-generated>
using System.Reflection;

namespace FxResources.System.Runtime.Serialization.Formatters
{
	internal static class SR { }
}
namespace System
{
	internal static partial class SR
	{
		private static global::System.Resources.ResourceManager s_resourceManager;
		internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(FxResources.System.Runtime.Serialization.Formatters.SR)));

		/// <summary>Hashtable's capacity overflowed and went negative. Check load factor, capacity and the current size of the table.</summary>
		internal static string @Arg_HTCapacityOverflow => GetResourceString("Arg_HTCapacityOverflow", @"Hashtable's capacity overflowed and went negative. Check load factor, capacity and the current size of the table.");
		/// <summary>Type '{0}' in Assembly '{1}' is not marked as serializable.</summary>
		internal static string @Serialization_NonSerType => GetResourceString("Serialization_NonSerType", @"Type '{0}' in Assembly '{1}' is not marked as serializable.");
		/// <summary>Parameters 'members' and 'data' must have the same length.</summary>
		internal static string @Argument_DataLengthDifferent => GetResourceString("Argument_DataLengthDifferent", @"Parameters 'members' and 'data' must have the same length.");
		/// <summary>Member at position {0} was null.</summary>
		internal static string @ArgumentNull_NullMember => GetResourceString("ArgumentNull_NullMember", @"Member at position {0} was null.");
		/// <summary>Only FieldInfo, PropertyInfo, and SerializationMemberInfo are recognized.</summary>
		internal static string @Serialization_UnknownMemberInfo => GetResourceString("Serialization_UnknownMemberInfo", @"Only FieldInfo, PropertyInfo, and SerializationMemberInfo are recognized.");
		/// <summary>Object has never been assigned an objectID.</summary>
		internal static string @Serialization_NoID => GetResourceString("Serialization_NoID", @"Object has never been assigned an objectID.");
		/// <summary>The internal array cannot expand to greater than Int32.MaxValue elements.</summary>
		internal static string @Serialization_TooManyElements => GetResourceString("Serialization_TooManyElements", @"The internal array cannot expand to greater than Int32.MaxValue elements.");
		/// <summary>The FieldInfo object is not valid.</summary>
		internal static string @Argument_InvalidFieldInfo => GetResourceString("Argument_InvalidFieldInfo", @"The FieldInfo object is not valid.");
		/// <summary>A fixup is registered to the object with ID {0}, but the object does not appear in the graph.</summary>
		internal static string @Serialization_NeverSeen => GetResourceString("Serialization_NeverSeen", @"A fixup is registered to the object with ID {0}, but the object does not appear in the graph.");
		/// <summary>The object with ID {0} implements the IObjectReference interface for which all dependencies cannot be resolved. The likely cause is two instances of IObjectReference that have a mutual dependency on each other.</summary>
		internal static string @Serialization_IORIncomplete => GetResourceString("Serialization_IORIncomplete", @"The object with ID {0} implements the IObjectReference interface for which all dependencies cannot be resolved. The likely cause is two instances of IObjectReference that have a mutual dependency on each other.");
		/// <summary>The object with ID {0} was referenced in a fixup but does not exist.</summary>
		internal static string @Serialization_ObjectNotSupplied => GetResourceString("Serialization_ObjectNotSupplied", @"The object with ID {0} was referenced in a fixup but does not exist.");
		/// <summary>{0}.SetObjectData returns a value that is neither null nor equal to the first parameter. Such Surrogates cannot be part of cyclical reference.</summary>
		internal static string @Serialization_NotCyclicallyReferenceableSurrogate => GetResourceString("Serialization_NotCyclicallyReferenceableSurrogate", @"{0}.SetObjectData returns a value that is neither null nor equal to the first parameter. Such Surrogates cannot be part of cyclical reference.");
		/// <summary>The implementation of the IObjectReference interface returns too many nested references to other objects that implement IObjectReference.</summary>
		internal static string @Serialization_TooManyReferences => GetResourceString("Serialization_TooManyReferences", @"The implementation of the IObjectReference interface returns too many nested references to other objects that implement IObjectReference.");
		/// <summary>The object with ID {0} was referenced in a fixup but has not been registered.</summary>
		internal static string @Serialization_MissingObject => GetResourceString("Serialization_MissingObject", @"The object with ID {0} was referenced in a fixup but has not been registered.");
		/// <summary>A fixup on an object implementing ISerializable or having a surrogate was discovered for an object which does not have a SerializationInfo available.</summary>
		internal static string @Serialization_InvalidFixupDiscovered => GetResourceString("Serialization_InvalidFixupDiscovered", @"A fixup on an object implementing ISerializable or having a surrogate was discovered for an object which does not have a SerializationInfo available.");
		/// <summary>Unable to load type {0} required for deserialization.</summary>
		internal static string @Serialization_TypeLoadFailure => GetResourceString("Serialization_TypeLoadFailure", @"Unable to load type {0} required for deserialization.");
		/// <summary>ValueType fixup on Arrays is not implemented.</summary>
		internal static string @Serialization_ValueTypeFixup => GetResourceString("Serialization_ValueTypeFixup", @"ValueType fixup on Arrays is not implemented.");
		/// <summary>Fixing up a partially available ValueType chain is not implemented.</summary>
		internal static string @Serialization_PartialValueTypeFixup => GetResourceString("Serialization_PartialValueTypeFixup", @"Fixing up a partially available ValueType chain is not implemented.");
		/// <summary>Cannot perform fixup.</summary>
		internal static string @Serialization_UnableToFixup => GetResourceString("Serialization_UnableToFixup", @"Cannot perform fixup.");
		/// <summary>objectID cannot be less than or equal to zero.</summary>
		internal static string @ArgumentOutOfRange_ObjectID => GetResourceString("ArgumentOutOfRange_ObjectID", @"objectID cannot be less than or equal to zero.");
		/// <summary>An object cannot be registered twice.</summary>
		internal static string @Serialization_RegisterTwice => GetResourceString("Serialization_RegisterTwice", @"An object cannot be registered twice.");
		/// <summary>The given object does not implement the ISerializable interface.</summary>
		internal static string @Serialization_NotISer => GetResourceString("Serialization_NotISer", @"The given object does not implement the ISerializable interface.");
		/// <summary>The constructor to deserialize an object of type '{0}' was not found.</summary>
		internal static string @Serialization_ConstructorNotFound => GetResourceString("Serialization_ConstructorNotFound", @"The constructor to deserialize an object of type '{0}' was not found.");
		/// <summary>The ObjectManager found an invalid number of fixups. This usually indicates a problem in the Formatter.</summary>
		internal static string @Serialization_IncorrectNumberOfFixups => GetResourceString("Serialization_IncorrectNumberOfFixups", @"The ObjectManager found an invalid number of fixups. This usually indicates a problem in the Formatter.");
		/// <summary>A member fixup was registered for an object which implements ISerializable or has a surrogate. In this situation, a delayed fixup must be used.</summary>
		internal static string @Serialization_InvalidFixupType => GetResourceString("Serialization_InvalidFixupType", @"A member fixup was registered for an object which implements ISerializable or has a surrogate. In this situation, a delayed fixup must be used.");
		/// <summary>Object IDs must be greater than zero.</summary>
		internal static string @Serialization_IdTooSmall => GetResourceString("Serialization_IdTooSmall", @"Object IDs must be greater than zero.");
		/// <summary>The ID of the containing object cannot be the same as the object ID.</summary>
		internal static string @Serialization_ParentChildIdentical => GetResourceString("Serialization_ParentChildIdentical", @"The ID of the containing object cannot be the same as the object ID.");
		/// <summary>Only system-provided types can be passed to the GetUninitializedObject method. '{0}' is not a valid instance of a type.</summary>
		internal static string @Serialization_InvalidType => GetResourceString("Serialization_InvalidType", @"Only system-provided types can be passed to the GetUninitializedObject method. '{0}' is not a valid instance of a type.");
		/// <summary>Type must be a runtime Type object.</summary>
		internal static string @Argument_MustBeRuntimeType => GetResourceString("Argument_MustBeRuntimeType");
		/// <summary>When supplying the ID of a containing object, the FieldInfo that identifies the current field within that object must also be supplied.</summary>
		internal static string @Argument_MustSupplyParent => GetResourceString("Argument_MustSupplyParent", @"When supplying the ID of a containing object, the FieldInfo that identifies the current field within that object must also be supplied.");
		/// <summary>Cannot supply both a MemberInfo and an Array to indicate the parent of a value type.</summary>
		internal static string @Argument_MemberAndArray => GetResourceString("Argument_MemberAndArray", @"Cannot supply both a MemberInfo and an Array to indicate the parent of a value type.");
		/// <summary>Invalid BinaryFormatter stream.</summary>
		internal static string @Serialization_CorruptedStream => GetResourceString("Serialization_CorruptedStream", @"Invalid BinaryFormatter stream.");
		/// <summary>Attempting to deserialize an empty stream.</summary>
		internal static string @Serialization_Stream => GetResourceString("Serialization_Stream", @"Attempting to deserialize an empty stream.");
		/// <summary>Binary stream '{0}' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.</summary>
		internal static string @Serialization_BinaryHeader => GetResourceString("Serialization_BinaryHeader", @"Binary stream '{0}' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.");
		/// <summary>Invalid expected type.</summary>
		internal static string @Serialization_TypeExpected => GetResourceString("Serialization_TypeExpected", @"Invalid expected type.");
		/// <summary>End of Stream encountered before parsing was completed.</summary>
		internal static string @Serialization_StreamEnd => GetResourceString("Serialization_StreamEnd", @"End of Stream encountered before parsing was completed.");
		/// <summary>Cross-AppDomain BinaryFormatter error; expected '{0}' but received '{1}'.</summary>
		internal static string @Serialization_CrossAppDomainError => GetResourceString("Serialization_CrossAppDomainError", @"Cross-AppDomain BinaryFormatter error; expected '{0}' but received '{1}'.");
		/// <summary>No map for object '{0}'.</summary>
		internal static string @Serialization_Map => GetResourceString("Serialization_Map", @"No map for object '{0}'.");
		/// <summary>No assembly information is available for object on the wire, '{0}'.</summary>
		internal static string @Serialization_Assembly => GetResourceString("Serialization_Assembly", @"No assembly information is available for object on the wire, '{0}'.");
		/// <summary>Invalid ObjectTypeEnum {0}.</summary>
		internal static string @Serialization_ObjectTypeEnum => GetResourceString("Serialization_ObjectTypeEnum", @"Invalid ObjectTypeEnum {0}.");
		/// <summary>No assembly ID for object type '{0}'.</summary>
		internal static string @Serialization_AssemblyId => GetResourceString("Serialization_AssemblyId", @"No assembly ID for object type '{0}'.");
		/// <summary>Invalid array type '{0}'.</summary>
		internal static string @Serialization_ArrayType => GetResourceString("Serialization_ArrayType", @"Invalid array type '{0}'.");
		/// <summary>Invalid type code in stream '{0}'.</summary>
		internal static string @Serialization_TypeCode => GetResourceString("Serialization_TypeCode", @"Invalid type code in stream '{0}'.");
		/// <summary>Invalid write type request '{0}'.</summary>
		internal static string @Serialization_TypeWrite => GetResourceString("Serialization_TypeWrite", @"Invalid write type request '{0}'.");
		/// <summary>Invalid read type request '{0}'.</summary>
		internal static string @Serialization_TypeRead => GetResourceString("Serialization_TypeRead", @"Invalid read type request '{0}'.");
		/// <summary>Unable to find assembly '{0}'.</summary>
		internal static string @Serialization_AssemblyNotFound => GetResourceString("Serialization_AssemblyNotFound", @"Unable to find assembly '{0}'.");
		/// <summary>The input stream is not a valid binary format. The starting contents (in bytes) are: {0} ...</summary>
		internal static string @Serialization_InvalidFormat => GetResourceString("Serialization_InvalidFormat", @"The input stream is not a valid binary format. The starting contents (in bytes) are: {0} ...");
		/// <summary>No top object.</summary>
		internal static string @Serialization_TopObject => GetResourceString("Serialization_TopObject", @"No top object.");
		/// <summary>Invalid element '{0}'.</summary>
		internal static string @Serialization_XMLElement => GetResourceString("Serialization_XMLElement", @"Invalid element '{0}'.");
		/// <summary>Top object cannot be instantiated for element '{0}'.</summary>
		internal static string @Serialization_TopObjectInstantiate => GetResourceString("Serialization_TopObjectInstantiate", @"Top object cannot be instantiated for element '{0}'.");
		/// <summary>Array element type is Object, 'dt' attribute is null.</summary>
		internal static string @Serialization_ArrayTypeObject => GetResourceString("Serialization_ArrayTypeObject", @"Array element type is Object, 'dt' attribute is null.");
		/// <summary>Type is missing for member of type Object '{0}'.</summary>
		internal static string @Serialization_TypeMissing => GetResourceString("Serialization_TypeMissing", @"Type is missing for member of type Object '{0}'.");
		/// <summary>Object {0} has never been assigned an objectID.</summary>
		internal static string @Serialization_ObjNoID => GetResourceString("Serialization_ObjNoID", @"Object {0} has never been assigned an objectID.");
		/// <summary>MemberInfo type {0} cannot be serialized.</summary>
		internal static string @Serialization_SerMemberInfo => GetResourceString("Serialization_SerMemberInfo", @"MemberInfo type {0} cannot be serialized.");
		/// <summary>When supplying a FieldInfo for fixing up a nested type, a valid ID for that containing object must also be supplied.</summary>
		internal static string @Argument_MustSupplyContainer => GetResourceString("Argument_MustSupplyContainer", @"When supplying a FieldInfo for fixing up a nested type, a valid ID for that containing object must also be supplied.");

		/// <summary>Non existent ParameterInfo. Position bigger than member's parameters length.</summary>
		internal static string @Serialization_BadParameterInfo => GetResourceString("Serialization_BadParameterInfo");
		/// <summary>The value of the field '{0}' is invalid.  The serialized data is corrupt.</summary>
		internal static string @Serialization_CorruptField => GetResourceString("Serialization_CorruptField");
		/// <summary>Invalid serialized DateTime data. Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks.</summary>
		internal static string @Serialization_DateTimeTicksOutOfRange => GetResourceString("Serialization_DateTimeTicksOutOfRange");
		/// <summary>Serializing delegates is not supported on this platform.</summary>
		internal static string @Serialization_DelegatesNotSupported => GetResourceString("Serialization_DelegatesNotSupported");
		/// <summary>Insufficient state to return the real object.</summary>
		internal static string @Serialization_InsufficientState => GetResourceString("Serialization_InsufficientState");
		/// <summary>An error occurred while deserializing the object.  The serialized data is corrupt.</summary>
		internal static string @Serialization_InvalidData => GetResourceString("Serialization_InvalidData");
		/// <summary>The serialized data contained an invalid escape sequence '\\{0}'.</summary>
		internal static string @Serialization_InvalidEscapeSequence => GetResourceString("Serialization_InvalidEscapeSequence");
		/// <summary>OnDeserialization method was called while the object was not being deserialized.</summary>
		internal static string @Serialization_InvalidOnDeser => GetResourceString("Serialization_InvalidOnDeser");
		/// <summary>An IntPtr or UIntPtr with an eight byte value cannot be deserialized on a machine with a four byte word size.</summary>
		internal static string @Serialization_InvalidPtrValue => GetResourceString("Serialization_InvalidPtrValue");
		/// <summary>The keys and values arrays have different sizes.</summary>
		internal static string @Serialization_KeyValueDifferentSizes => GetResourceString("Serialization_KeyValueDifferentSizes");
		/// <summary>Invalid serialized DateTime data. Unable to find 'ticks' or 'dateData'.</summary>
		internal static string @Serialization_MissingDateTimeData => GetResourceString("Serialization_MissingDateTimeData");
		/// <summary>The Keys for this Hashtable are missing.</summary>
		internal static string @Serialization_MissingKeys => GetResourceString("Serialization_MissingKeys");
		/// <summary>The values for this dictionary are missing.</summary>
		internal static string @Serialization_MissingValues => GetResourceString("Serialization_MissingValues");
		/// <summary>Serialized member does not have a ParameterInfo.</summary>
		internal static string @Serialization_NoParameterInfo => GetResourceString("Serialization_NoParameterInfo");
		/// <summary>Member '{0}' was not found.</summary>
		internal static string @Serialization_NotFound => GetResourceString("Serialization_NotFound");
		/// <summary>One of the serialized keys is null.</summary>
		internal static string @Serialization_NullKey => GetResourceString("Serialization_NullKey");
		/// <summary>Version value must be positive.</summary>
		internal static string @Serialization_OptionalFieldVersionValue => GetResourceString("Serialization_OptionalFieldVersionValue");
		/// <summary>Cannot add the same member twice to a SerializationInfo object.</summary>
		internal static string @Serialization_SameNameTwice => GetResourceString("Serialization_SameNameTwice");
		/// <summary>The serialized Capacity property of StringBuilder must be positive, less than or equal to MaxCapacity and greater than or equal to the String length.</summary>
		internal static string @Serialization_StringBuilderCapacity => GetResourceString("Serialization_StringBuilderCapacity");
		/// <summary>The serialized MaxCapacity property of StringBuilder must be positive and greater than or equal to the String length.</summary>
		internal static string @Serialization_StringBuilderMaxCapacity => GetResourceString("Serialization_StringBuilderMaxCapacity");
		/// <summary>Setter must have parameters.</summary>



		/// <summary>Parse error. Current element is not compatible with the next element, {0}.</summary>
		internal static string @Serialization_ParseError => GetResourceString("Serialization_ParseError", @"Parse error. Current element is not compatible with the next element, {0}.");
		/// <summary>MemberInfo requested for ISerializable type.</summary>
		internal static string @Serialization_ISerializableMemberInfo => GetResourceString("Serialization_ISerializableMemberInfo", @"MemberInfo requested for ISerializable type.");
		/// <summary>MemberInfo cannot be obtained for ISerialized Object '{0}'.</summary>
		internal static string @Serialization_MemberInfo => GetResourceString("Serialization_MemberInfo", @"MemberInfo cannot be obtained for ISerialized Object '{0}'.");
		/// <summary>Types not available for ISerializable object '{0}'.</summary>
		internal static string @Serialization_ISerializableTypes => GetResourceString("Serialization_ISerializableTypes", @"Types not available for ISerializable object '{0}'.");
		/// <summary>Member '{0}' in class '{1}' is not present in the serialized stream and is not marked with {2}.</summary>
		internal static string @Serialization_MissingMember => GetResourceString("Serialization_MissingMember", @"Member '{0}' in class '{1}' is not present in the serialized stream and is not marked with {2}.");
		/// <summary>No MemberInfo for Object {0}.</summary>
		internal static string @Serialization_NoMemberInfo => GetResourceString("Serialization_NoMemberInfo", @"No MemberInfo for Object {0}.");
		/// <summary>Selector contained a cycle.</summary>
		internal static string @Serialization_SurrogateCycleInArgument => GetResourceString("Serialization_SurrogateCycleInArgument", @"Selector contained a cycle.");
		/// <summary>Adding selector will introduce a cycle.</summary>
		internal static string @Serialization_SurrogateCycle => GetResourceString("Serialization_SurrogateCycle", @"Adding selector will introduce a cycle.");
		/// <summary>An action was attempted during deserialization that could lead to a security vulnerability. The action has been aborted.</summary>
		internal static string @Serialization_DangerousDeserialization => GetResourceString("Serialization_DangerousDeserialization");
		/// <summary>An action was attempted during deserialization that could lead to a security vulnerability. The action has been aborted. To allow the action, set the '{0}' AppContext switch to true.</summary>
		internal static string @Serialization_DangerousDeserialization_Switch => GetResourceString("Serialization_DangerousDeserialization_Switch");
		/// <summary>Enumeration has either not started or has already finished.</summary>
		internal static string @InvalidOperation_EnumOpCantHappen => GetResourceString("InvalidOperation_EnumOpCantHappen");

		/// <summary>Unable to read beyond the end of the stream.</summary>
		internal static string @IO_EOF_ReadBeyondEOF => GetResourceString("IO_EOF_ReadBeyondEOF", @"Unable to read beyond the end of the stream.");
		/// <summary>BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.</summary>
		internal static string @BinaryFormatter_SerializationDisallowed => GetResourceString("BinaryFormatter_SerializationDisallowed", @"BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.");
		/// <summary>BinaryFormatter serialization and deserialization are not supported on this platform. See https://aka.ms/binaryformatter for more information.</summary>
		internal static string @BinaryFormatter_SerializationNotSupportedOnThisPlatform => GetResourceString("BinaryFormatter_SerializationNotSupportedOnThisPlatform", @"BinaryFormatter serialization and deserialization are not supported on this platform. See https://aka.ms/binaryformatter for more information.");

	}
}
