#nullable disable
namespace System.Web.Security
{
  internal class DefaultMembershipAdapter : IMembershipAdapter
  {
    public MembershipProviderCollection Providers
    {
      get
      {
        throw new PlatformNotSupportedException(ApplicationServicesStrings.Platform_not_supported);
      }
    }

    public int UserIsOnlineTimeWindow
    {
      get
      {
        throw new PlatformNotSupportedException(ApplicationServicesStrings.Platform_not_supported);
      }
    }

    public bool IsDecryptionKeyAutogenerated
    {
      get
      {
        throw new PlatformNotSupportedException(ApplicationServicesStrings.Platform_not_supported);
      }
    }

    public bool UsingCustomEncryption
    {
      get
      {
        throw new PlatformNotSupportedException(ApplicationServicesStrings.Platform_not_supported);
      }
    }

    public byte[] EncryptOrDecryptData(bool encrypt, byte[] buffer, bool useLegacyMode)
    {
      throw new PlatformNotSupportedException(ApplicationServicesStrings.Platform_not_supported);
    }
  }
}
