//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("Estrellas de Esperanza")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2025 Estrellas de Esperanza.")]
[assembly: System.Reflection.AssemblyFileVersion("10.0.14")]
[assembly: System.Reflection.AssemblyVersion("10.0.14")]
[assembly: System.Reflection.AssemblyInformationalVersion("10.0.14")]
[assembly: System.Resources.SatelliteContractVersion("10.0.14")]


